### ISSUE TITLE
Add analytics tracking 

### ISSUE THREAD

**Issue by Jared-Sprague** [CommandLineHeroes/clh-bash#38]
to know how many times the game has been played

**Comment by Venefilyn** [comment]
Just wanted to say there's a few alternatives to this. 

The obvious choice would be Google Analytics, as it's "free" to use. Though there are open-source self-hosted alternatives if that is something we'd want and have servers for:

* Matamo (formerly Piwik) https://matomo.org/ - Open sourced with GPL-3.0
* Fathom Analytics https://usefathom.com/ - Open sourced with MIT

Otherwise if we just want one metric we can send a POST request to a server indicating that a game has started
